name: Build and deploy .NET application to Container App silo

on:
  push:
    branches:
    - main
env:
  CONTAINER_APP_CONTAINER_NAME: silo
  CONTAINER_APP_NAME: silo
  CONTAINER_APP_RESOURCE_GROUP_NAME: bradyg-HelloOrleans
  CONTAINER_REGISTRY_LOGIN_SERVER: helloorleansregistry.azurecr.io
  DOCKER_FILE_PATH: HelloOrleans.Silo/Dockerfile
  PROJECT_NAME_FOR_DOCKER: helloorleanssilo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.helloorleansregistry_USERNAME_FFFF }}
        password: ${{ secrets.helloorleansregistry_PASSWORD_FFFF }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.silo_SPN }}

    - name: Installing Container Apps extension
      uses: azure/CLI@v1
      with:
        inlineScript: >
          echo "Installing containerapp extension"
          az extension add --name containerapp --yes

    - name: Deploy Silo
      uses: azure/CLI@v1
      with:
        inlineScript: >
          echo "Deploying Silo"

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} -i ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }} --registry-login-server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --registry-username  ${{ secrets.REGISTRY_USERNAME }} --registry-password ${{ secrets.REGISTRY_PASSWORD }} --debug

    - name: logout
      run: >
        az logout
